spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
  application:
    name: order

env:
  dev4
girl:
  name: lili
  age: 20
