spring:
  rabbitmq:
    host: 192.168.44.129
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true  
server:
  port: 8082    
    
